In [12]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


torch.tensors 
read through : https://pytorch.org/docs/stable/tensors.html

In [13]:
#scalar,0 dim tensor
scalar=torch.tensor(10)
scalar
scalar.ndim

#get tensor back as int
scalar.item()

10

In [14]:
#vector
vector=torch.tensor([5,7])
vector.ndim
vector.shape

torch.Size([2])

In [15]:
#matrix
matrix=torch.tensor([[3,4]
                     ,[7,8]])
matrix
matrix.shape
matrix.ndim

2

In [16]:
#tensor
tensor1=torch.tensor([[[1,2,3],[3,2,1]],[[4,5,6],[6,5,4]]])
tensor1
tensor1.ndim
tensor1.shape


torch.Size([2, 2, 3])

### Random Tensors


In [17]:
random_tensor=torch.rand(3,4)
random_tensor

tensor([[0.7875, 0.1419, 0.7030, 0.4424],
        [0.2894, 0.9262, 0.5484, 0.4520],
        [0.3291, 0.5868, 0.6282, 0.7922]])

### Zeros and Ones

In [18]:
random_zeros=torch.zeros(size=(3,4))
random_zeros
random_ones=torch.ones(size=(3,4))
random_ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

### Range of tensors

In [19]:
tensor_range=torch.arange(start=1,end=50,step=5)
tensor_range
tensor_like=torch.zeros_like(tensor_range)
tensor_like

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [20]:
some_tensor=torch.rand(4,5)
some_tensor

tensor([[0.4169, 0.4574, 0.5332, 0.9560, 0.8677],
        [0.5773, 0.2185, 0.6000, 0.6868, 0.9732],
        [0.1550, 0.3824, 0.8111, 0.4653, 0.2410],
        [0.4811, 0.8335, 0.3370, 0.6923, 0.3131]])

### Tensor Multiplication

In [21]:
tensor_A=torch.rand(4,5)
tensor_B=torch.rand(5,5)
##Mul1=torch.matmul(tensor_A,tensor_B)
Mul1=torch.mm(tensor_A,tensor_B)
Mul1

tensor([[1.2286, 1.0775, 0.7178, 1.3448, 1.1654],
        [1.4149, 1.5206, 0.9965, 1.5610, 1.1977],
        [0.8801, 0.8899, 0.9855, 1.0707, 0.3613],
        [1.2220, 1.4939, 1.1527, 1.8801, 1.0443]])

In [22]:
tensor_C=torch.rand(4,5)
tensor_D=torch.rand(4,5)
Mul1=torch.mm(tensor_C,tensor_D)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (4x5 and 4x5)

Change the shape of one tensor using a 
#### transpose: Switches the axes or dimensions of given tensor

In [24]:
Mul1=torch.mm(tensor_C,tensor_D.T) ##the second tensor has been transposed
Mul1

tensor([[1.1479, 0.9780, 1.6141, 0.7811],
        [1.1076, 1.5403, 1.9076, 1.0423],
        [0.6586, 0.5466, 0.9555, 0.4767],
        [0.8429, 1.0602, 1.4900, 0.8812]])

In [26]:
tensor_C.shape, tensor_C.size()

(torch.Size([4, 5]), torch.Size([4, 5]))

### Min, Max and Median of a Tensor

In [ ]:
##min
torch.min(tensor_A),tensor_A.min()

##max
torch.max(tensor_A),tensor_A.max()

## mean: the mean() function requires the tensor to be float32 datatype
torch.mean(tensor_A.type(torch.float32)), (tensor_A.type(torch.float32)).mean()

## finding positional min or max
tensor_A.argmin(), tensor_A.argmax()


### Reshaping, Viewing, Stacking
<u>Reshaping</u>: reshape reshapes an input tensor to a defined shape.<br>
<u>Viewing</u> :shows a view of an input tensor of a certain shape, but keep the same memory as the original tensor.<br>
<u>Stacking</u>: combining multiple tensors on top of each other(vstack) or side by side (hstack) or just stack with a dim<br>


In [35]:
tensor_A.reshape(5,4)

tensor_x=tensor_A
z=tensor_x.view(4,5)
z


tensor([[2.9666e-01, 4.3348e-01, 2.1505e-01, 8.4330e-01, 6.2450e-01],
        [4.3419e-01, 9.0635e-01, 5.5143e-01, 4.4250e-01, 4.3347e-01],
        [7.5310e-04, 1.1161e-01, 8.1804e-01, 2.3401e-02, 7.1167e-01],
        [5.2761e-01, 4.7561e-01, 6.7226e-01, 1.9879e-01, 9.7664e-01]])

In [41]:
tensor_y=torch.arange(1,9)
## tensor([1, 2, 3, 4, 5, 6, 7, 8])

tensor_y_stacked_ver=torch.stack([tensor_y,tensor_y,tensor_y], dim=0)
tensor_y_stacked_hor=torch.stack([tensor_y,tensor_y,tensor_y], dim=1)
tensor_y_stacked_ver, tensor_y_stacked_hor



(tensor([[1, 2, 3, 4, 5, 6, 7, 8],
         [1, 2, 3, 4, 5, 6, 7, 8],
         [1, 2, 3, 4, 5, 6, 7, 8]]),
 tensor([[1, 1, 1],
         [2, 2, 2],
         [3, 3, 3],
         [4, 4, 4],
         [5, 5, 5],
         [6, 6, 6],
         [7, 7, 7],
         [8, 8, 8]]))

### Squeezing, Unsqueezing, Permute
<u>Squeezing</u>: Removes all '1' dimensions from tensor<br>
<u>unsquuezing</u>: add a '1' dimension to the tensor<br>
<u>Permute</u>: which return a view of the input with dimensions permuted(swapped) in a certain way.