In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


c:\Users\sheli\anaconda3\envs\SheliaWorkspace\lib\site-packages\tqdm\auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


torch.tensors 
read through : https://pytorch.org/docs/stable/tensors.html

In [2]:
#scalar,0 dim tensor
scalar=torch.tensor(10)
scalar
scalar.ndim

#get tensor back as int
scalar.item()

10

In [3]:
#vector
vector=torch.tensor([5,7])
vector.ndim
vector.shape

torch.Size([2])

In [4]:
#matrix
matrix=torch.tensor([[3,4]
                     ,[7,8]])
matrix
matrix.shape
matrix.ndim

2

In [5]:
#tensor
tensor1=torch.tensor([[[1,2,3],[3,2,1]],[[4,5,6],[6,5,4]]])
tensor1
tensor1.ndim
tensor1.shape


torch.Size([2, 2, 3])

### Random Tensors


In [6]:
random_tensor=torch.rand(3,4)
random_tensor

tensor([[0.5316, 0.6409, 0.4934, 0.8927],
        [0.7512, 0.2033, 0.9915, 0.4179],
        [0.1282, 0.9020, 0.6024, 0.5426]])

### Zeros and Ones

In [7]:
random_zeros=torch.zeros(size=(3,4))
random_zeros
random_ones=torch.ones(size=(3,4))
random_ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

### Range of tensors

In [8]:
tensor_range=torch.arange(start=1,end=50,step=5)
tensor_range
tensor_like=torch.zeros_like(tensor_range)
tensor_like

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [10]:
some_tensor=torch.rand(4,5)
some_tensor

tensor([[0.4774, 0.9816, 0.1085, 0.9115, 0.0661],
        [0.7455, 0.1202, 0.7838, 0.2048, 0.2304],
        [0.5039, 0.3017, 0.9234, 0.1183, 0.6898],
        [0.4827, 0.5474, 0.6843, 0.4969, 0.4116]])