In [3]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


/home/shelia/anaconda3/envs/tf-gpu/lib/python3.9/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


torch.tensors 
read through : https://pytorch.org/docs/stable/tensors.html

In [4]:
#scalar,0 dim tensor
scalar=torch.tensor(10)
scalar
scalar.ndim

#get tensor back as int
scalar.item()

10

In [5]:
#vector
vector=torch.tensor([5,7])
vector.ndim
vector.shape

torch.Size([2])

In [6]:
#matrix
matrix=torch.tensor([[3,4]
                     ,[7,8]])
matrix
matrix.shape
matrix.ndim

2

In [7]:
#tensor
tensor1=torch.tensor([[[1,2,3],[3,2,1]],[[4,5,6],[6,5,4]]])
tensor1
tensor1.ndim
tensor1.shape


torch.Size([2, 2, 3])

### Random Tensors


In [8]:
random_tensor=torch.rand(3,4)
random_tensor

tensor([[0.9549, 0.3681, 0.8291, 0.5517],
        [0.9425, 0.4516, 0.3033, 0.8618],
        [0.6788, 0.5945, 0.6946, 0.6712]])

### Zeros and Ones

In [9]:
random_zeros=torch.zeros(size=(3,4))
random_zeros
random_ones=torch.ones(size=(3,4))
random_ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

### Range of tensors

In [10]:
tensor_range=torch.arange(start=1,end=50,step=5)
tensor_range
tensor_like=torch.zeros_like(tensor_range)
tensor_like

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [11]:
some_tensor=torch.rand(4,5)
some_tensor

tensor([[3.3403e-01, 3.6418e-01, 9.0132e-01, 4.9694e-01, 5.7173e-01],
        [2.1554e-01, 8.9322e-01, 9.6105e-01, 3.7644e-01, 5.7891e-01],
        [6.6904e-01, 8.7022e-01, 8.9049e-04, 4.8071e-01, 5.9592e-01],
        [8.5294e-01, 9.7300e-01, 6.0927e-02, 3.8027e-01, 4.8419e-02]])

### Tensor Multiplication

In [12]:
tensor_A=torch.rand(4,5)
tensor_B=torch.rand(5,5)
##Mul1=torch.matmul(tensor_A,tensor_B)
Mul1=torch.mm(tensor_A,tensor_B)
Mul1

tensor([[1.0836, 0.7626, 0.6542, 1.3456, 1.5473],
        [1.8751, 1.2199, 1.9382, 2.8088, 2.9050],
        [1.4969, 0.8432, 1.4596, 1.6602, 1.8811],
        [0.9433, 0.5873, 0.6169, 1.0432, 0.9845]])

In [13]:
tensor_C=torch.rand(4,5)
tensor_D=torch.rand(4,5)
Mul1=torch.mm(tensor_C,tensor_D)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (4x5 and 4x5)

Change the shape of one tensor using a 
#### transpose: Switches the axes or dimensions of given tensor

In [15]:
Mul1=torch.mm(tensor_C,tensor_D.T) ##the second tensor has been transposed
Mul1

tensor([[0.7609, 0.2106, 0.5481, 0.8030],
        [0.4522, 0.1726, 0.5677, 1.1219],
        [0.6763, 0.2366, 0.7719, 0.9599],
        [1.4524, 0.4185, 1.3162, 1.9071]])

In [16]:
tensor_C.shape, tensor_C.size()

(torch.Size([4, 5]), torch.Size([4, 5]))

### Min, Max and Median of a Tensor

In [17]:
##min
torch.min(tensor_A),tensor_A.min()

##max
torch.max(tensor_A),tensor_A.max()

## mean: the mean() function requires the tensor to be float32 datatype
torch.mean(tensor_A.type(torch.float32)), (tensor_A.type(torch.float32)).mean()

## finding positional min or max
tensor_A.argmin(), tensor_A.argmax()


(tensor(3), tensor(6))

### Reshaping, Viewing, Stacking
<u>Reshaping</u>: reshape reshapes an input tensor to a defined shape.<br>
<u>Viewing</u> :shows a view of an input tensor of a certain shape, but keep the same memory as the original tensor.<br>
<u>Stacking</u>: combining multiple tensors on top of each other(vstack) or side by side (hstack) or just stack with a dim<br>


In [18]:
tensor_A.reshape(5,4)

tensor_x=tensor_A
z=tensor_x.view(4,5)
z


tensor([[0.6308, 0.7110, 0.5837, 0.0147, 0.0945],
        [0.9700, 0.9742, 0.4393, 0.5999, 0.9319],
        [0.6643, 0.5944, 0.3081, 0.9396, 0.0289],
        [0.5539, 0.1953, 0.5082, 0.1057, 0.0486]])

In [19]:
tensor_y=torch.arange(1,9)
## tensor([1, 2, 3, 4, 5, 6, 7, 8])

tensor_y_stacked_ver=torch.stack([tensor_y,tensor_y,tensor_y], dim=0)
tensor_y_stacked_hor=torch.stack([tensor_y,tensor_y,tensor_y], dim=1)
tensor_y_stacked_ver, tensor_y_stacked_hor



(tensor([[1, 2, 3, 4, 5, 6, 7, 8],
         [1, 2, 3, 4, 5, 6, 7, 8],
         [1, 2, 3, 4, 5, 6, 7, 8]]),
 tensor([[1, 1, 1],
         [2, 2, 2],
         [3, 3, 3],
         [4, 4, 4],
         [5, 5, 5],
         [6, 6, 6],
         [7, 7, 7],
         [8, 8, 8]]))

### Squeezing, Unsqueezing, Permute
<u>Squeezing</u>: Removes all '1' dimensions from tensor<br>
<u>unsquuezing</u>: add a '1' dimension to the tensor<br>
<u>Permute</u>: which return a view of the input with dimensions permuted(swapped) in a certain way.

In [20]:
tensor_sq=torch.zeros(2,1,2,1,2,1)
tensor_sq_s=tensor_sq.squeeze(dim=1) ##changes takes place to that particular dimension. (0 indexed)
tensor_sq_u=tensor_sq_s.unsqueeze(dim=1) ## Returns a new tensor with a dimension of size one inserted at the specified position
tensor_sq_s.shape,tensor_sq_u.shape


(torch.Size([2, 2, 1, 2, 1]), torch.Size([2, 1, 2, 1, 2, 1]))

In [21]:
tensor_perm=torch.zeros(5,3,4).permute(2,0,1)
tensor_perm.shape

torch.Size([4, 5, 3])

In [22]:
tensor_perm1=torch.rand(size=(3,4,5))
tensor_perm2=tensor_perm1.permute(2,0,1)
print(tensor_perm1)
print(tensor_perm2)

tensor([[[0.6696, 0.5699, 0.5370, 0.2008, 0.9641],
         [0.5115, 0.6914, 0.9754, 0.7301, 0.4748],
         [0.9183, 0.3748, 0.4181, 0.7369, 0.8707],
         [0.5807, 0.9205, 0.1938, 0.8367, 0.5578]],

        [[0.8022, 0.2188, 0.1888, 0.6634, 0.3265],
         [0.4247, 0.1939, 0.8174, 0.6046, 0.3545],
         [0.5730, 0.9230, 0.1703, 0.9807, 0.4453],
         [0.8969, 0.3425, 0.3194, 0.1199, 0.5096]],

        [[0.7911, 0.6110, 0.6503, 0.7845, 0.0125],
         [0.4766, 0.0942, 0.9953, 0.6009, 0.3402],
         [0.4401, 0.8866, 0.0537, 0.6701, 0.7401],
         [0.4853, 0.8767, 0.1569, 0.8051, 0.8244]]])
tensor([[[0.6696, 0.5115, 0.9183, 0.5807],
         [0.8022, 0.4247, 0.5730, 0.8969],
         [0.7911, 0.4766, 0.4401, 0.4853]],

        [[0.5699, 0.6914, 0.3748, 0.9205],
         [0.2188, 0.1939, 0.9230, 0.3425],
         [0.6110, 0.0942, 0.8866, 0.8767]],

        [[0.5370, 0.9754, 0.4181, 0.1938],
         [0.1888, 0.8174, 0.1703, 0.3194],
         [0.6503, 0.9953, 0.0537, 

### Indexing and Slicing
[][]/[,] for indexing of a 2D tensor<br>
[: , :] == ',' between dimentions and ':' between the start and end index of a dimension 

In [23]:
tensor_index=torch.rand(4,5,3)
tensor_index

tensor([[[0.9439, 0.3967, 0.5634],
         [0.1911, 0.5520, 0.9006],
         [0.8067, 0.0769, 0.4478],
         [0.9872, 0.0702, 0.3163],
         [0.3679, 0.4006, 0.6925]],

        [[0.6744, 0.4712, 0.4131],
         [0.5468, 0.4612, 0.6376],
         [0.8786, 0.9139, 0.5539],
         [0.1438, 0.8844, 0.1900],
         [0.6033, 0.3050, 0.6821]],

        [[0.9902, 0.4478, 0.8806],
         [0.9198, 0.7535, 0.3794],
         [0.4867, 0.7855, 0.7532],
         [0.4268, 0.3223, 0.3402],
         [0.1567, 0.6794, 0.4621]],

        [[0.2876, 0.5909, 0.3371],
         [0.6393, 0.0510, 0.0633],
         [0.3123, 0.0349, 0.8803],
         [0.1875, 0.7334, 0.7129],
         [0.3673, 0.3466, 0.6482]]])

In [24]:
tensor_index[0][0], tensor_index[0:1,0:1,2:3]

(tensor([0.9439, 0.3967, 0.5634]), tensor([[[0.5634]]]))

### Numpy array to Tensor

In [25]:
## Numpy array default datatype is  reflected as the deafult datatype for torc datatype unless defined different and vice versa
## numpy and tensor doesn't share memory

array1=np.arange(1.0)
torch1=torch.from_numpy(array1) #converts numpy array to tensor
array2=torch1.numpy() # converst tensor to numpy array
array1.dtype,torch1.dtype,array2.dtype

(dtype('float64'), torch.float64, dtype('float64'))

In [29]:
### Reproducbility
### to reduce the randomness in neural networks, we can set the seed for the random number generator
rand_tensor_A=torch.rand(3,4) ##this may produce different results each time

#create some reproducable ones
random_seed=42 #most commmon seed
torch.manual_seed(random_seed) #call everytime before creating random numbers
rand_tensor_B=torch.rand(3,4)

torch.manual_seed(random_seed) 
rand_tensor_C=torch.rand(3,4)
print(rand_tensor_B==rand_tensor_C)

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


In [ ]:
###Extra resources for reproducability
# https://pytorch.org/docs/stable/notes/randomness.html

In [32]:
#Using GPU
#check if GPU is available
torch.cuda.is_available()
#set device
device=torch.device('cuda' if torch.cuda.is_available() else 'cpu')
torch.cuda.device_count()

### https://pytorch.org/docs/stable/notes/cuda.html#best-practices


1