# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [1]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [2]:
import torch


# Create random tensor
A=torch.rand(7,7)
A

tensor([[0.2388, 0.8458, 0.3013, 0.6010, 0.6891, 0.2918, 0.2376],
        [0.5459, 0.5532, 0.9868, 0.4679, 0.8646, 0.0619, 0.6034],
        [0.5204, 0.7074, 0.5173, 0.5581, 0.1262, 0.9636, 0.4051],
        [0.9822, 0.5224, 0.8338, 0.2065, 0.1296, 0.3445, 0.2253],
        [0.7563, 0.2299, 0.7120, 0.5954, 0.6026, 0.2102, 0.9014],
        [0.0295, 0.0446, 0.1818, 0.6587, 0.9700, 0.0461, 0.4460],
        [0.9396, 0.3041, 0.7353, 0.1278, 0.6045, 0.6189, 0.5183]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [5]:
# Create another random tensor
B=torch.rand(1,7)

# Perform matrix multiplication 
C=torch.mm(A,B.T)
C


tensor([[1.4815],
        [1.8434],
        [2.2110],
        [1.9247],
        [1.9198],
        [0.6842],
        [2.0529]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [11]:
# Set manual seed
random_seed=0
torch.manual_seed(random_seed)


# Create two random tensors

C=torch.rand(5,5)

torch.manual_seed(random_seed)
D=torch.rand(5,1)

# Matrix multiply tensors
E=torch.mm(C,D)
E


tensor([[0.9562],
        [1.0250],
        [0.5964],
        [0.9721],
        [1.3208]])

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [12]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)




### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [28]:
# Set random seed
torch.manual_seed(1234)

# Check for access to GPU
device=torch.device('cuda' if torch.cuda.is_available() else 'cuda')


# Create two random tensors on GPU
D=torch.rand(2,3,device=device)
E=torch.rand(2,3,device=device)
D,E


(tensor([[0.1272, 0.8167, 0.5440],
         [0.6601, 0.2721, 0.9737]], device='cuda:0'),
 tensor([[0.6208, 0.0276, 0.3255],
         [0.1114, 0.6812, 0.3608]], device='cuda:0'))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [29]:
# Perform matmul on tensor_A and tensor_B
F=torch.mm(D,E.T)
F

tensor([[0.2786, 0.7668],
        [0.7343, 0.6102]], device='cuda:0')

### 8. Find the maximum and minimum values of the output of 7.

In [24]:
# Find max
m=torch.max(F)

# Find min
n=torch.min(F)

m,n


(tensor(0.7668, device='cuda:0'), tensor(0.2786, device='cuda:0'))

### 9. Find the maximum and minimum index values of the output of 7.

In [35]:
# Find arg max
G=torch.tensor([[0.7343, 0.6102],
              [0.2786, 0.7668]],device=device)
mp=G.argmax()

# Find arg min
np=G.argmin(keepdim=True)
mp,np


(tensor(3, device='cuda:0'), tensor([[2]], device='cuda:0'))


### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [52]:
# Set seed

torch.manual_seed(42)
# Create random tensor

ranT=torch.rand(1,1,1,10)
# Remove single dimensions
ranT_sq=ranT.squeeze(dim=1) #[1,(1),1,10]

ranT_sq=ranT_sq.squeeze(dim=1)#[1,(1),10]
ranT_sq=ranT_sq.squeeze(dim=0) #[(1),10]
#ranT_sq=ranT_sq.squeeze(dim=1)


# Print out tensors and their shapes
print(ranT,"\n", ranT_sq, "\n", ranT_sq.shape)


tensor([[[[0.8823, 0.9150, 0.3829, 0.9593, 0.3904, 0.6009, 0.2566, 0.7936,
           0.9408, 0.1332]]]]) 
 tensor([0.8823, 0.9150, 0.3829, 0.9593, 0.3904, 0.6009, 0.2566, 0.7936, 0.9408,
        0.1332]) 
 torch.Size([10])
