In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


/home/shelia/anaconda3/envs/tf-gpu/lib/python3.9/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


torch.tensors 
read through : https://pytorch.org/docs/stable/tensors.html

In [3]:
#scalar,0 dim tensor
scalar=torch.tensor(10)
scalar
scalar.ndim

#get tensor back as int
scalar.item()

10

In [4]:
#vector
vector=torch.tensor([5,7])
vector.ndim
vector.shape

torch.Size([2])

In [5]:
#matrix
matrix=torch.tensor([[3,4]
                     ,[7,8]])
matrix
matrix.shape
matrix.ndim

2

In [6]:
#tensor
tensor1=torch.tensor([[[1,2,3],[3,2,1]],[[4,5,6],[6,5,4]]])
tensor1
tensor1.ndim
tensor1.shape


torch.Size([2, 2, 3])

### Random Tensors


In [7]:
random_tensor=torch.rand(3,4)
random_tensor

tensor([[0.0735, 0.5254, 0.4590, 0.4699],
        [0.4762, 0.9943, 0.8366, 0.9299],
        [0.9905, 0.7957, 0.7278, 0.6078]])

### Zeros and Ones

In [8]:
random_zeros=torch.zeros(size=(3,4))
random_zeros
random_ones=torch.ones(size=(3,4))
random_ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

### Range of tensors

In [9]:
tensor_range=torch.arange(start=1,end=50,step=5)
tensor_range
tensor_like=torch.zeros_like(tensor_range)
tensor_like

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [10]:
some_tensor=torch.rand(4,5)
some_tensor

tensor([[0.2694, 0.6825, 0.4186, 0.1738, 0.1353],
        [0.7373, 0.5876, 0.9439, 0.6510, 0.5909],
        [0.7615, 0.6051, 0.0717, 0.6901, 0.3604],
        [0.3471, 0.2269, 0.0903, 0.8551, 0.5453]])

### Tensor Multiplication

In [11]:
tensor_A=torch.rand(4,5)
tensor_B=torch.rand(5,5)
##Mul1=torch.matmul(tensor_A,tensor_B)
Mul1=torch.mm(tensor_A,tensor_B)
Mul1

tensor([[0.3261, 2.1314, 1.5827, 1.2192, 1.8822],
        [0.7910, 2.4458, 1.7543, 1.3632, 1.6237],
        [0.1280, 1.5130, 1.1849, 1.0087, 1.2724],
        [0.5953, 1.2649, 0.8851, 0.6613, 0.5514]])

In [12]:
tensor_C=torch.rand(4,5)
tensor_D=torch.rand(4,5)
Mul1=torch.mm(tensor_C,tensor_D)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (4x5 and 4x5)

Change the shape of one tensor using a 
#### transpose: Switches the axes or dimensions of given tensor

In [14]:
Mul1=torch.mm(tensor_C,tensor_D.T) ##the second tensor has been transposed
Mul1

tensor([[0.7506, 1.4536, 1.0407, 1.5544],
        [0.9853, 1.5996, 1.6619, 1.5256],
        [1.2127, 2.3342, 1.8268, 2.4787],
        [1.0550, 1.9443, 1.2083, 1.8943]])

In [15]:
tensor_C.shape, tensor_C.size()

(torch.Size([4, 5]), torch.Size([4, 5]))

### Min, Max and Median of a Tensor

In [16]:
##min
torch.min(tensor_A),tensor_A.min()

##max
torch.max(tensor_A),tensor_A.max()

## mean: the mean() function requires the tensor to be float32 datatype
torch.mean(tensor_A.type(torch.float32)), (tensor_A.type(torch.float32)).mean()

## finding positional min or max
tensor_A.argmin(), tensor_A.argmax()


(tensor(15), tensor(1))

### Reshaping, Viewing, Stacking
<u>Reshaping</u>: reshape reshapes an input tensor to a defined shape.<br>
<u>Viewing</u> :shows a view of an input tensor of a certain shape, but keep the same memory as the original tensor.<br>
<u>Stacking</u>: combining multiple tensors on top of each other(vstack) or side by side (hstack) or just stack with a dim<br>


In [17]:
tensor_A.reshape(5,4)

tensor_x=tensor_A
z=tensor_x.view(4,5)
z


tensor([[0.8329, 0.9941, 0.0680, 0.4634, 0.3855],
        [0.3265, 0.7862, 0.7807, 0.8992, 0.5518],
        [0.5549, 0.9171, 0.0969, 0.0267, 0.4332],
        [0.0119, 0.0640, 0.7372, 0.6067, 0.3909]])

In [18]:
tensor_y=torch.arange(1,9)
## tensor([1, 2, 3, 4, 5, 6, 7, 8])

tensor_y_stacked_ver=torch.stack([tensor_y,tensor_y,tensor_y], dim=0)
tensor_y_stacked_hor=torch.stack([tensor_y,tensor_y,tensor_y], dim=1)
tensor_y_stacked_ver, tensor_y_stacked_hor



(tensor([[1, 2, 3, 4, 5, 6, 7, 8],
         [1, 2, 3, 4, 5, 6, 7, 8],
         [1, 2, 3, 4, 5, 6, 7, 8]]),
 tensor([[1, 1, 1],
         [2, 2, 2],
         [3, 3, 3],
         [4, 4, 4],
         [5, 5, 5],
         [6, 6, 6],
         [7, 7, 7],
         [8, 8, 8]]))

### Squeezing, Unsqueezing, Permute
<u>Squeezing</u>: Removes all '1' dimensions from tensor<br>
<u>unsquuezing</u>: add a '1' dimension to the tensor<br>
<u>Permute</u>: which return a view of the input with dimensions permuted(swapped) in a certain way.

In [40]:
tensor_sq=torch.zeros(2,1,2,1,2,1)
tensor_sq_s=tensor_sq.squeeze(dim=1) ##changes takes plave to that particular dimension. (o indexed)
tensor_sq_u=tensor_sq_s.unsqueeze(dim=1)
tensor_sq_s.shape,tensor_sq_u.shape


(torch.Size([2, 2, 1, 2, 1]), torch.Size([2, 1, 2, 1, 2, 1]))

In [42]:
tensor_perm=torch.zeros(5,3,4).permute(2,0,1)
tensor_perm.shape

torch.Size([4, 5, 3])

### Indexing and Slicing
[][]/[,] for indexing of a 2D tensor<br>
[: , :] : ',' between dimentions and ':' between the start and end index of a dimension 

In [108]:
tensor_index=torch.rand(4,5,3)
tensor_index

tensor([[[0.5490, 0.6883, 0.8428],
         [0.0970, 0.2960, 0.3370],
         [0.7356, 0.9155, 0.0410],
         [0.2296, 0.1162, 0.6674],
         [0.7605, 0.7307, 0.5002]],

        [[0.7079, 0.2843, 0.6508],
         [0.6507, 0.3130, 0.5273],
         [0.2369, 0.9118, 0.4946],
         [0.8863, 0.5384, 0.3566],
         [0.4357, 0.9673, 0.8902]],

        [[0.9523, 0.9697, 0.3076],
         [0.5298, 0.5272, 0.6091],
         [0.1045, 0.4098, 0.6811],
         [0.7462, 0.4749, 0.4890],
         [0.0684, 0.1168, 0.6923]],

        [[0.5395, 0.4400, 0.6795],
         [0.5025, 0.5819, 0.0039],
         [0.5093, 0.5867, 0.7036],
         [0.5387, 0.3805, 0.1363],
         [0.6688, 0.7293, 0.1593]]])

In [125]:
tensor_index[0][0], tensor_index[0:1,0:1,2:3]

(tensor([0.5490, 0.6883, 0.8428]), tensor([[[0.8428]]]))