In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


c:\Users\sheli\anaconda3\envs\SheliaWorkspace\lib\site-packages\tqdm\auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


torch.tensors 
read through : https://pytorch.org/docs/stable/tensors.html

In [3]:
#scalar,0 dim tensor
scalar=torch.tensor(10)
scalar
scalar.ndim

#get tensor back as int
scalar.item()

10

In [4]:
#vector
vector=torch.tensor([5,7])
vector.ndim
vector.shape

torch.Size([2])

In [5]:
#matrix
matrix=torch.tensor([[3,4]
                     ,[7,8]])
matrix
matrix.shape
matrix.ndim

2

In [6]:
#tensor
tensor1=torch.tensor([[[1,2,3],[3,2,1]],[[4,5,6],[6,5,4]]])
tensor1
tensor1.ndim
tensor1.shape


torch.Size([2, 2, 3])

### Random Tensors


In [7]:
random_tensor=torch.rand(3,4)
random_tensor

tensor([[0.5153, 0.1714, 0.3254, 0.2632],
        [0.6155, 0.2657, 0.9826, 0.1269],
        [0.0093, 0.1921, 0.6494, 0.1344]])

### Zeros and Ones

In [8]:
random_zeros=torch.zeros(size=(3,4))
random_zeros
random_ones=torch.ones(size=(3,4))
random_ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

### Range of tensors

In [9]:
tensor_range=torch.arange(start=1,end=50,step=5)
tensor_range
tensor_like=torch.zeros_like(tensor_range)
tensor_like

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [10]:
some_tensor=torch.rand(4,5)
some_tensor

tensor([[0.3611, 0.0679, 0.4882, 0.3414, 0.9158],
        [0.0499, 0.8925, 0.4473, 0.6803, 0.5886],
        [0.8541, 0.8887, 0.1628, 0.6773, 0.7128],
        [0.1091, 0.6099, 0.7653, 0.6368, 0.5863]])

### Tensor Multiplication

In [11]:
tensor_A=torch.rand(4,5)
tensor_B=torch.rand(5,5)
##Mul1=torch.matmul(tensor_A,tensor_B)
Mul1=torch.mm(tensor_A,tensor_B)
Mul1

tensor([[1.3327, 1.9264, 1.3203, 1.0502, 1.9139],
        [1.6449, 1.9167, 1.1783, 0.9978, 1.2848],
        [1.6009, 1.5450, 1.4517, 1.3133, 1.8405],
        [1.6592, 1.9318, 1.2242, 1.0359, 1.2831]])

In [12]:
tensor_C=torch.rand(4,5)
tensor_D=torch.rand(4,5)
Mul1=torch.mm(tensor_C,tensor_D)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (4x5 and 4x5)

Change the shape of one tensor using a 
#### transpose: Switches the axes or dimensions of given tensor

In [ ]:
Mul1=torch.mm(tensor_C,tensor_D.T) ##the second tensor has been transposed

NameError: name 'torch' is not defined