In [24]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


torch.tensors 
read through : https://pytorch.org/docs/stable/tensors.html

In [25]:
#scalar,0 dim tensor
scalar=torch.tensor(10)
scalar
scalar.ndim

#get tensor back as int
scalar.item()

10

In [26]:
#vector
vector=torch.tensor([5,7])
vector.ndim
vector.shape

torch.Size([2])

In [27]:
#matrix
matrix=torch.tensor([[3,4]
                     ,[7,8]])
matrix
matrix.shape
matrix.ndim

2

In [28]:
#tensor
tensor1=torch.tensor([[[1,2,3],[3,2,1]],[[4,5,6],[6,5,4]]])
tensor1
tensor1.ndim
tensor1.shape


torch.Size([2, 2, 3])

### Random Tensors


In [29]:
random_tensor=torch.rand(3,4)
random_tensor

tensor([[0.1560, 0.2910, 0.1686, 0.3063],
        [0.0615, 0.7387, 0.0093, 0.7298],
        [0.2020, 0.6085, 0.2720, 0.3195]])

### Zeros and Ones

In [30]:
random_zeros=torch.zeros(size=(3,4))
random_zeros
random_ones=torch.ones(size=(3,4))
random_ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

### Range of tensors

In [31]:
tensor_range=torch.arange(start=1,end=50,step=5)
tensor_range
tensor_like=torch.zeros_like(tensor_range)
tensor_like

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [32]:
some_tensor=torch.rand(4,5)
some_tensor

tensor([[0.7618, 0.0161, 0.3717, 0.5134, 0.7370],
        [0.0312, 0.1096, 0.5345, 0.7217, 0.4007],
        [0.0891, 0.1170, 0.3410, 0.2910, 0.6746],
        [0.5632, 0.2169, 0.7754, 0.6254, 0.4927]])

### Tensor Multiplication

In [33]:
tensor_A=torch.rand(4,5)
tensor_B=torch.rand(5,5)
##Mul1=torch.matmul(tensor_A,tensor_B)
Mul1=torch.mm(tensor_A,tensor_B)
Mul1

tensor([[1.5796, 2.1817, 2.1769, 1.2924, 2.8761],
        [0.8149, 1.4153, 1.6009, 1.0600, 2.2049],
        [0.6721, 0.7010, 0.8605, 0.7471, 0.9678],
        [1.2014, 1.9081, 1.5891, 1.2220, 2.0997]])

In [34]:
tensor_C=torch.rand(4,5)
tensor_D=torch.rand(4,5)
Mul1=torch.mm(tensor_C,tensor_D)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (4x5 and 4x5)

Change the shape of one tensor using a 
#### transpose: Switches the axes or dimensions of given tensor

In [35]:
Mul1=torch.mm(tensor_C,tensor_D.T) ##the second tensor has been transposed