In [4]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


torch.tensors 
read through : https://pytorch.org/docs/stable/tensors.html

In [5]:
#scalar,0 dim tensor
scalar=torch.tensor(10)
scalar
scalar.ndim

#get tensor back as int
scalar.item()

10

In [6]:
#vector
vector=torch.tensor([5,7])
vector.ndim
vector.shape

torch.Size([2])

In [7]:
#matrix
matrix=torch.tensor([[3,4]
                     ,[7,8]])
matrix
matrix.shape
matrix.ndim

2

In [8]:
#tensor
tensor1=torch.tensor([[[1,2,3],[3,2,1]],[[4,5,6],[6,5,4]]])
tensor1
tensor1.ndim
tensor1.shape


torch.Size([2, 2, 3])

### Random Tensors


In [9]:
random_tensor=torch.rand(3,4)
random_tensor

tensor([[0.9444, 0.6710, 0.9983, 0.6860],
        [0.0677, 0.1883, 0.3459, 0.2011],
        [0.1245, 0.7504, 0.2938, 0.5711]])

### Zeros and Ones

In [10]:
random_zeros=torch.zeros(size=(3,4))
random_zeros
random_ones=torch.ones(size=(3,4))
random_ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

### Range of tensors

In [11]:
tensor_range=torch.arange(start=1,end=50,step=5)
tensor_range
tensor_like=torch.zeros_like(tensor_range)
tensor_like

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [12]:
some_tensor=torch.rand(4,5)
some_tensor

tensor([[0.4125, 0.3438, 0.6834, 0.0798, 0.5489],
        [0.9695, 0.6907, 0.4296, 0.2941, 0.9381],
        [0.4461, 0.3387, 0.1795, 0.8275, 0.7110],
        [0.7142, 0.8640, 0.6502, 0.6544, 0.3058]])

### Tensor Multiplication

In [13]:
tensor_A=torch.rand(4,5)
tensor_B=torch.rand(5,5)
##Mul1=torch.matmul(tensor_A,tensor_B)
Mul1=torch.mm(tensor_A,tensor_B)
Mul1

tensor([[1.9067, 1.9823, 1.7742, 1.4339, 0.9164],
        [0.7818, 0.5653, 0.5612, 0.7187, 0.4238],
        [1.0896, 1.4332, 1.3384, 1.2121, 0.4924],
        [0.3340, 0.5605, 0.5233, 0.4319, 0.1541]])

In [14]:
tensor_C=torch.rand(4,5)
tensor_D=torch.rand(4,5)
Mul1=torch.mm(tensor_C,tensor_D)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (4x5 and 4x5)

Change the shape of one tensor using a 
#### transpose: Switches the axes or dimensions of given tensor

In [15]:
Mul1=torch.mm(tensor_C,tensor_D.T) ##the second tensor has been transposed
Mul1

tensor([[1.5421, 0.7441, 1.4771, 1.6335],
        [0.7391, 0.3777, 0.8260, 0.7477],
        [0.6027, 0.4860, 0.8675, 0.6915],
        [1.5799, 1.3862, 2.2012, 2.1141]])

In [16]:
tensor_C.shape, tensor_C.size()

(torch.Size([4, 5]), torch.Size([4, 5]))

### Min, Max and Median of a Tensor

In [17]:
##min
torch.min(tensor_A),tensor_A.min()

##max
torch.max(tensor_A),tensor_A.max()

## mean: the mean() function requires the tensor to be float32 datatype
torch.mean(tensor_A.type(torch.float32)), (tensor_A.type(torch.float32)).mean()

## finding positional min or max
tensor_A.argmin(), tensor_A.argmax()


(tensor(11), tensor(3))

### Reshaping, Viewing, Stacking
<u>Reshaping</u>: reshape reshapes an input tensor to a defined shape.<br>
<u>Viewing</u> :shows a view of an input tensor of a certain shape, but keep the same memory as the original tensor.<br>
<u>Stacking</u>: combining multiple tensors on top of each other(vstack) or side by side (hstack) or just stack with a dim<br>


In [18]:
tensor_A.reshape(5,4)

tensor_x=tensor_A
z=tensor_x.view(4,5)
z


tensor([[8.2174e-01, 2.5373e-01, 5.0803e-01, 9.9719e-01, 2.6509e-01],
        [5.8536e-01, 2.1487e-02, 1.1326e-01, 4.5345e-02, 3.4086e-01],
        [6.5797e-01, 5.7238e-04, 8.4903e-01, 2.7177e-01, 2.9507e-01],
        [1.8247e-01, 1.5660e-02, 3.7453e-01, 6.2689e-02, 1.2335e-01]])

In [19]:
tensor_y=torch.arange(1,9)
## tensor([1, 2, 3, 4, 5, 6, 7, 8])

tensor_y_stacked_ver=torch.stack([tensor_y,tensor_y,tensor_y], dim=0)
tensor_y_stacked_hor=torch.stack([tensor_y,tensor_y,tensor_y], dim=1)
tensor_y_stacked_ver, tensor_y_stacked_hor



(tensor([[1, 2, 3, 4, 5, 6, 7, 8],
         [1, 2, 3, 4, 5, 6, 7, 8],
         [1, 2, 3, 4, 5, 6, 7, 8]]),
 tensor([[1, 1, 1],
         [2, 2, 2],
         [3, 3, 3],
         [4, 4, 4],
         [5, 5, 5],
         [6, 6, 6],
         [7, 7, 7],
         [8, 8, 8]]))

### Squeezing, Unsqueezing, Permute
<u>Squeezing</u>: Removes all '1' dimensions from tensor<br>
<u>unsquuezing</u>: add a '1' dimension to the tensor<br>
<u>Permute</u>: which return a view of the input with dimensions permuted(swapped) in a certain way.

In [20]:
tensor_sq=torch.zeros(2,1,2,1,2,1)
tensor_sq_s=tensor_sq.squeeze(dim=1) ##changes takes place to that particular dimension. (0 indexed)
tensor_sq_u=tensor_sq_s.unsqueeze(dim=1) ## Returns a new tensor with a dimension of size one inserted at the specified position
tensor_sq_s.shape,tensor_sq_u.shape


(torch.Size([2, 2, 1, 2, 1]), torch.Size([2, 1, 2, 1, 2, 1]))

In [21]:
tensor_perm=torch.zeros(5,3,4).permute(2,0,1)
tensor_perm.shape

torch.Size([4, 5, 3])

In [25]:
tensor_perm1=torch.rand(size=(3,4,5))
tensor_perm2=tensor_perm1.permute(2,0,1)
print(tensor_perm1)
print(tensor_perm2)

tensor([[[0.4387, 0.7986, 0.7937, 0.5872, 0.2777],
         [0.7125, 0.9407, 0.7912, 0.2892, 0.1855],
         [0.4948, 0.0810, 0.6458, 0.6925, 0.1486],
         [0.4224, 0.7832, 0.0890, 0.6796, 0.7920]],

        [[0.6873, 0.2097, 0.9326, 0.9293, 0.0209],
         [0.6810, 0.3170, 0.4537, 0.1983, 0.1684],
         [0.8907, 0.9700, 0.6557, 0.4173, 0.7181],
         [0.8650, 0.1405, 0.6417, 0.9522, 0.4049]],

        [[0.5749, 0.4503, 0.4273, 0.4375, 0.0296],
         [0.2671, 0.1904, 0.1402, 0.6759, 0.4718],
         [0.5561, 0.7625, 0.5295, 0.1244, 0.5517],
         [0.5306, 0.3229, 0.9096, 0.2832, 0.0107]]])
tensor([[[0.4387, 0.7125, 0.4948, 0.4224],
         [0.6873, 0.6810, 0.8907, 0.8650],
         [0.5749, 0.2671, 0.5561, 0.5306]],

        [[0.7986, 0.9407, 0.0810, 0.7832],
         [0.2097, 0.3170, 0.9700, 0.1405],
         [0.4503, 0.1904, 0.7625, 0.3229]],

        [[0.7937, 0.7912, 0.6458, 0.0890],
         [0.9326, 0.4537, 0.6557, 0.6417],
         [0.4273, 0.1402, 0.5295, 

### Indexing and Slicing
[][]/[,] for indexing of a 2D tensor<br>
[: , :] == ',' between dimentions and ':' between the start and end index of a dimension 

In [22]:
tensor_index=torch.rand(4,5,3)
tensor_index

tensor([[[0.2275, 0.8829, 0.2155],
         [0.2492, 0.3177, 0.0391],
         [0.7192, 0.6340, 0.3424],
         [0.3558, 0.1763, 0.6150],
         [0.7549, 0.2930, 0.3009]],

        [[0.1431, 0.3665, 0.8019],
         [0.5048, 0.6680, 0.4654],
         [0.8124, 0.7155, 0.6275],
         [0.1505, 0.7009, 0.7470],
         [0.2831, 0.4080, 0.5800]],

        [[0.1304, 0.1733, 0.4632],
         [0.8708, 0.6318, 0.6444],
         [0.1580, 0.9833, 0.0940],
         [0.0666, 0.7640, 0.6579],
         [0.0039, 0.9914, 0.4353]],

        [[0.0105, 0.9677, 0.9859],
         [0.0221, 0.1895, 0.8960],
         [0.4822, 0.3574, 0.0494],
         [0.0806, 0.4355, 0.5023],
         [0.8662, 0.4661, 0.0279]]])

In [23]:
tensor_index[0][0], tensor_index[0:1,0:1,2:3]

(tensor([0.2275, 0.8829, 0.2155]), tensor([[[0.2155]]]))

### Numpy array to Tensor

In [29]:
## Numpy array default datatype is  reflected as the deafult datatype for torc datatype unless defined different and vice versa
## numpy and tensor doesn't share memory

array1=np.arange(1.0)
torch1=torch.from_numpy(array1) #converts numpy array to tensor
array2=torch1.numpy() # converst tensor to numpy array
array1.dtype,torch1.dtype,array2.dtype

(dtype('float64'), torch.float64, dtype('float64'))